learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# so that we can point to our paths here using relative paths
app_name = 'basic_app' # always set this to whatever the application's name is
# allows us to use template tagging.

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {"text":'hello world', "number": 100}
    return render(request, 'basic_app/index.html', context=context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html> 
<!-- the above should always be the first line in an HTML page -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>
<!-- all of the stuff on this page is stuff that we want to appear on every page -->
    <div class="container">

        {% block body_block %}
            <!-- Anything outside of this will be inherited if you extend! -->
        {% endblock %}
    </div>


</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
    {% extends "basic_app/base.html" %}
    {% load my_extras %}
    <!-- to use your custom tags, you must load them in. -->
    {% block body_block %}
        <!-- <h1>WELCOME TO INDEX</h1> -->
        <h2>This is index.html page showing.</h2>
        <!-- <a href="{% url 'basic_app:relative' %}">RELATIVE</a>
        <a href="{% url 'basic_app:other' %}">OTHER</a>
        <a href="{% url 'admin:index' %}">ADMIN</a> -->
        <h1>{{ text|cutt:'hello' }} {{ number|add:"99" }}</h1>
            <!-- {{ contextvar|filter:"parameter"} -->
            <!-- these are called template filters - go see the documentation for more -->
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
<!-- always of form: extends "template_directory_path/file_name.html" -->
    <!-- <a href="{% url 'basic_app:relative' %}">RELATIVE</a>
    <a href="{% url 'index' %}">HOME</a>
    <a href="{% url 'admin:index' %}">ADMIN</a> -->
        <!-- note that this tag uses the convention: app_name:path_name, both of which are defined in the app urls file -->
    {% block body_block %}
        <!-- what is between these blocks will be in the place of body_block on base.html, the file we are extending
            this one with.
        -->
        <h1>WELCOME TO OTHER!</h1>
        <h2>This is an example of template inheritance!</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">OTHER</a>
    <a href="{% url 'index' %}">HOME</a>
    <a href="{% url 'admin:index' %}">ADMIN</a>
    <!-- note that this tag uses the convention: app_name:path_name, both of which are defined in the app urls file -->
    <!-- if the routes are defined in teh project root, just use the name (as defined in the path) of the path. -->
</body>
</html>